# THIS FILE WAS AUTOGENERATED. DO NOT EDIT.

from pydantic import BaseModel, UUID4
from datetime import datetime, date
from typing import List, Dict, Any, Optional
from decimal import Decimal
from ipaddress import IPv4Address, IPv6Address
from datetime import timedelta


class List(BaseModel):
    created_at: datetime
    id: str
    list_name: str
    type: Optional[str] = None
    user_id: str

class ListItem(BaseModel):
    artist: Optional[str] = None
    created_at: datetime
    id: str
    list_id: Optional[str] = None
    title: Optional[str] = None
    value: Optional[str] = None

class Song(BaseModel):
    artist: str
    created_at: datetime
    hiragana_lyrics: Optional[dict] = None
    id: str
    image_url: Optional[str] = None
    lyrics: Optional[dict] = None
    title: str
    word_mapping: Optional[dict] = None

class SongData(BaseModel):
    artist: str
    created_at: datetime
    hiragana_lyrics: Optional[dict] = None
    image_url: Optional[str] = None
    kanji_data: Optional[dict] = None
    lyrics: Optional[dict] = None
    title: str
    word_mapping: Optional[dict] = None

class User(BaseModel):
    created_at: datetime
    email: Optional[str] = None
    first_name: Optional[str] = None
    id: str
    last_name: Optional[str] = None
    username: Optional[str] = None
