
name: Gakuji FastAPI Image CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: "us-east-2"
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 533267207624.dkr.ecr.us-east-2.amazonaws.com
      - name: Build Docker image
        run: docker build -t gakuji-api .
      - name: Tag Docker image
        run: docker tag gakuji-api:latest 533267207624.dkr.ecr.us-east-2.amazonaws.com/gakuji-api:latest
      - name: Push Docker image
        run: docker push 533267207624.dkr.ecr.us-east-2.amazonaws.com/gakuji-api:latest
      - name: Build Docker Image for process-lines
        run: docker build -t process-lines ./longRunningFunction
      - name: Tag Docker image for process-lines
        run: docker tag process-lines:latest 533267207624.dkr.ecr.us-east-2.amazonaws.com/process-lines:latest
      - name: Push Docker image for process-lines
        run: docker push 533267207624.dkr.ecr.us-east-2.amazonaws.com/process-lines:latest


      - name: Update Lambda function code
        run: |
            aws lambda update-function-code \
            --function-name gakuji-api \
            --image-uri 533267207624.dkr.ecr.us-east-2.amazonaws.com/gakuji-api:latest \
            --region "us-east-2"

      - name: Wait for lambda to complete update
        run: bash ./scripts/wait_for_lambda.sh gakuji-api
      - name: Health Check API
        run: bash ./scripts/health_check.sh
